import React, { useState, useEffect } from 'react';
import posService from '../services/pos.service';
import { useAuth } from '../context/AuthContext';
import {
  Receipt,
  Search,
  RefreshCw,
  CheckCircle2,
  Clock,
  Check,
  Eye,
  X,
  FileText,
  AlertCircle
} from 'lucide-react';

export default function WaiterBillsView() {
  const { restaurant, addToast } = useAuth();
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filterState, setFilterState] = useState('ALL');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedBill, setSelectedBill] = useState(null);
  const [actionLoading, setActionLoading] = useState(null);

  const fetchBills = async () => {
    try {
      const res = await posService.billing.getBills();
      if (res.success && res.data) {
        setBills(res.data);
      }
    } catch (err) {
      addToast(err.message || 'Failed to fetch bills', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBills();
    const interval = setInterval(fetchBills, 8000);
    return () => clearInterval(interval);
  }, []);

  const handleDeliver = async (billId, tableNumber) => {
    setActionLoading(billId);
    try {
      await posService.waiter.deliverBill(billId);
      addToast(`Bill delivered to Table #${tableNumber}!`, 'success');
      fetchBills();
      if (selectedBill && selectedBill.id === billId) {
        setSelectedBill((prev) => ({ ...prev, isDelivered: true, deliveredAt: new Date() }));
      }
    } catch (err) {
      addToast(err.message || 'Failed to mark bill delivered', 'error');
    } finally {
      setActionLoading(null);
    }
  };

  const currency = restaurant?.currency || '₹';

  const filteredBills = bills.filter((b) => {
    const tableNum = b.order?.table?.tableNumber ? String(b.order.table.tableNumber) : '';
    const matchSearch =
      b.billNumber.toLowerCase().includes(searchQuery.toLowerCase()) ||
      tableNum.toLowerCase().includes(searchQuery.toLowerCase());

    if (!matchSearch) return false;
    if (filterState === 'ALL') return true;
    if (filterState === 'READY_TO_DELIVER') return !b.isDelivered && b.status === 'UNPAID';
    if (filterState === 'DELIVERED') return b.isDelivered;
    if (filterState === 'PAID') return b.status === 'PAID';
    return true;
  });

  return (
    <div className="w-full px-4 sm:px-6 lg:px-8 py-6 space-y-6 min-w-0">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-5 rounded-2xl border border-[#E5D8C6] shadow-sandstone">
        <div>
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-[#FAF7F2] border border-[#E5D8C6] rounded-xl text-[#92400E]">
              <Receipt className="w-6 h-6" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-[#1F2937] flex items-center gap-2">
                Guest Bills & Delivery Dispatch
                <span className="text-xs px-2.5 py-0.5 rounded-full bg-[#FAF7F2] text-[#5B6470] border border-[#E5D8C6] font-medium">
                  Read Only
                </span>
              </h1>
              <p className="text-xs text-[#5B6470]">
                View bills generated by Receptionist and record table delivery
              </p>
            </div>
          </div>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap items-center gap-3">
          <div className="relative">
            <Search className="w-4 h-4 text-[#5B6470] absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search bill # or table..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="bg-[#FAF7F2] border border-[#E5D8C6] rounded-xl pl-9 pr-3 py-1.5 text-xs text-[#1F2937] placeholder-[#5B6470] focus:outline-none focus:border-[#92400E] focus:ring-1 focus:ring-[#92400E]"
            />
          </div>

          <div className="flex items-center gap-1 bg-[#FAF7F2] p-1 rounded-xl border border-[#E5D8C6] text-xs">
            {[
              { id: 'ALL', label: 'All Bills' },
              { id: 'READY_TO_DELIVER', label: 'Ready to Deliver' },
              { id: 'DELIVERED', label: 'Delivered' },
              { id: 'PAID', label: 'Paid & Closed' },
            ].map((st) => (
              <button
                key={st.id}
                onClick={() => setFilterState(st.id)}
                className={`px-3 py-1 rounded-lg font-semibold transition cursor-pointer ${
                  filterState === st.id ? 'bg-[#92400E] text-white shadow-sandstone' : 'text-[#5B6470] hover:text-[#1F2937] hover:bg-[#F1E8DB]'
                }`}
              >
                {st.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Bills List */}
      <div className="bg-white border border-[#E5D8C6] rounded-2xl overflow-hidden shadow-sandstone">
        {loading ? (
          <div className="py-20 flex justify-center items-center text-[#5B6470] text-sm">
            <RefreshCw className="w-6 h-6 animate-spin text-[#92400E] mr-2" />
            Loading guest bills...
          </div>
        ) : filteredBills.length === 0 ? (
          <div className="text-center py-16 text-[#9CA3AF] text-sm">
            No bills found matching your filter.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-[#FAF7F2] text-[#5B6470] uppercase tracking-wider text-[11px] border-b border-[#E5D8C6]">
                <tr>
                  <th className="py-3.5 px-4 font-semibold">Bill #</th>
                  <th className="py-3.5 px-4 font-semibold">Table</th>
                  <th className="py-3.5 px-4 font-semibold">Order Ref</th>
                  <th className="py-3.5 px-4 font-semibold">Total Amount</th>
                  <th className="py-3.5 px-4 font-semibold">Bill Status</th>
                  <th className="py-3.5 px-4 font-semibold">Delivery State</th>
                  <th className="py-3.5 px-4 font-semibold text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E5D8C6] text-[#1F2937]">
                {filteredBills.map((b) => {
                  const tableNumber = b.order?.table?.tableNumber || 'Counter';
                  const isDelivered = b.isDelivered;
                  const isPaid = b.status === 'PAID';

                  return (
                    <tr
                      key={b.id}
                      className={`hover:bg-[#F1E8DB]/40 transition ${
                        !isDelivered && !isPaid ? 'bg-blue-50/30' : ''
                      }`}
                    >
                      <td className="py-3.5 px-4 font-mono font-bold text-[#1F2937]">
                        {b.billNumber}
                      </td>
                      <td className="py-3.5 px-4">
                        <span className="font-semibold text-[#1F2937]">
                          Table #{tableNumber}
                        </span>
                      </td>
                      <td className="py-3.5 px-4 font-mono text-[#5B6470] text-[11px]">
                        #{b.order?.orderNumber || 'N/A'}
                      </td>
                      <td className="py-3.5 px-4 font-mono font-bold text-[#92400E] text-sm">
                        {currency}
                        {Number(b.totalAmount).toFixed(2)}
                      </td>
                      <td className="py-3.5 px-4">
                        <span
                          className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase border ${
                            isPaid
                              ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                              : 'bg-amber-50 text-amber-900 border-amber-200'
                          }`}
                        >
                          {b.status}
                        </span>
                      </td>
                      <td className="py-3.5 px-4">
                        {isDelivered ? (
                          <span className="inline-flex items-center gap-1 text-teal-700 font-semibold text-[11px]">
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            Delivered
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 text-[#2563EB] font-bold text-[11px] animate-pulse">
                            <Clock className="w-3.5 h-3.5" />
                            Ready to Deliver
                          </span>
                        )}
                      </td>
                      <td className="py-3.5 px-4 text-right">
                        <div className="flex items-center justify-end gap-2">
                          {!isDelivered && (
                            <button
                              onClick={() => handleDeliver(b.id, tableNumber)}
                              disabled={actionLoading === b.id}
                              className="px-3 py-1.5 bg-[#2563EB] hover:bg-[#1D4ED8] text-white font-bold rounded-lg text-xs shadow-sandstone flex items-center gap-1 cursor-pointer"
                            >
                              <Check className="w-3.5 h-3.5" />
                              Deliver Bill
                            </button>
                          )}
                          <button
                            onClick={() => setSelectedBill(b)}
                            className="p-1.5 bg-[#FAF7F2] hover:bg-[#F1E8DB] text-[#5B6470] hover:text-[#1F2937] rounded-lg border border-[#E5D8C6] shadow-sandstone transition cursor-pointer"
                            title="Inspect Receipt"
                          >
                            <Eye className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Bill Preview Modal */}
      {selectedBill && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm">
          <div className="bg-white border border-[#E5D8C6] rounded-2xl w-full max-w-sm p-6 shadow-sandstone-lg space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-[#E5D8C6]">
              <div className="flex items-center gap-2">
                <FileText className="w-5 h-5 text-[#92400E]" />
                <h3 className="font-bold text-[#1F2937] text-base">Guest Check Receipt</h3>
              </div>
              <button
                onClick={() => setSelectedBill(null)}
                className="p-1.5 text-[#5B6470] hover:text-[#1F2937] rounded-lg hover:bg-[#F1E8DB] cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Receipt Styling */}
            <div className="bg-[#FAF7F2] text-[#1F2937] p-5 rounded-xl border border-[#E5D8C6] space-y-3 font-mono text-xs shadow-inner">
              <div className="text-center pb-2 border-b border-dashed border-[#E5D8C6]">
                <h4 className="font-extrabold text-sm uppercase text-[#1F2937]">{restaurant?.name || 'Restaurant POS'}</h4>
                <p className="text-[10px] text-[#5B6470]">Official Guest Bill</p>
                <p className="text-[10px] text-[#1F2937] font-semibold mt-1">
                  Table #{selectedBill.order?.table?.tableNumber || 'Takeaway'} • Bill #{selectedBill.billNumber}
                </p>
              </div>

              {/* Items */}
              <div className="space-y-1 py-1 max-h-40 overflow-y-auto">
                {selectedBill.order?.items?.map((item, idx) => (
                  <div key={idx} className="flex justify-between text-[11px]">
                    <span className="truncate pr-2 font-medium">
                      {item.quantity}x {item.menuItem?.name}
                    </span>
                    <span className="font-bold text-[#92400E]">
                      {currency}
                      {Number(item.subtotal || 0).toFixed(2)}
                    </span>
                  </div>
                ))}
              </div>

              {/* Financial Totals */}
              <div className="pt-2 border-t border-dashed border-[#E5D8C6] space-y-1 text-[11px]">
                <div className="flex justify-between text-[#5B6470]">
                  <span>Subtotal:</span>
                  <span>
                    {currency}
                    {Number(selectedBill.subtotal).toFixed(2)}
                  </span>
                </div>
                <div className="flex justify-between text-[#5B6470]">
                  <span>Tax ({Number(selectedBill.taxRate)}%):</span>
                  <span>
                    {currency}
                    {Number(selectedBill.taxAmount).toFixed(2)}
                  </span>
                </div>
                {Number(selectedBill.discountAmount) > 0 && (
                  <div className="flex justify-between text-emerald-700 font-semibold">
                    <span>Discount:</span>
                    <span>
                      -{currency}
                      {Number(selectedBill.discountAmount).toFixed(2)}
                    </span>
                  </div>
                )}
                <div className="flex justify-between text-sm font-extrabold pt-2 border-t border-[#1F2937] text-[#1F2937]">
                  <span>TOTAL DUE:</span>
                  <span className="text-[#92400E]">
                    {currency}
                    {Number(selectedBill.totalAmount).toFixed(2)}
                  </span>
                </div>
              </div>

              <div className="text-center pt-2 text-[10px] text-[#5B6470] border-t border-dashed border-[#E5D8C6]">
                Payment handled at front reception desk
              </div>
            </div>

            {/* Modal Actions */}
            <div className="flex gap-2 pt-2">
              {!selectedBill.isDelivered && (
                <button
                  onClick={() =>
                    handleDeliver(
                      selectedBill.id,
                      selectedBill.order?.table?.tableNumber || 'Counter'
                    )
                  }
                  className="flex-1 py-2.5 bg-[#2563EB] hover:bg-[#1D4ED8] text-white font-bold rounded-xl text-xs transition shadow-sandstone flex items-center justify-center gap-1.5 cursor-pointer"
                >
                  <Check className="w-4 h-4" />
                  Deliver Bill to Table
                </button>
              )}
              <button
                onClick={() => setSelectedBill(null)}
                className="flex-1 py-2.5 bg-[#FAF7F2] hover:bg-[#F1E8DB] text-[#1F2937] font-semibold rounded-xl text-xs border border-[#E5D8C6] shadow-sandstone transition cursor-pointer"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
